apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasteease-api-deployment
  namespace: tasteease
  labels:
    app: tasteease-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasteease-api-pod
  template:
    metadata:
      labels:
        app: tasteease-api-pod
    spec:
      containers:
        - name: tasteease-api
          image: estrng/tasteease:0.0.19
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: SECRETS_PATH
              value: /app/secrets/
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: secrets
          configMap:
            name: appsettings-taste-ease
