apiVersion: v1
kind: Service
metadata:
  name: tasteease-api-service
  labels:
    app: tasteease-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5212
      nodePort: 30002
  selector:
    app: tasteease-api-pod
